# Generated by Django 6.1a1 on 2026-06-26 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=128, verbose_name='登录密码')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='栏目名称')),
            ],
            options={
                'verbose_name': '新闻栏目',
                'verbose_name_plural': '新闻栏目',
                'db_table': 'news_type',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='公告内容')),
                ('author', models.CharField(blank=True, default='', max_length=50, verbose_name='发布人')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('news_type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.RESTRICT, related_name='news_list', to='news.newstype', verbose_name='所属栏目')),
            ],
            options={
                'verbose_name': '新闻公告',
                'verbose_name_plural': '新闻公告',
                'db_table': 'news',
                'ordering': ['-publish_time'],
            },
        ),
    ]
